Lesson 7
p0m1d0rka/thinknetika17 pull request #5
Opened 2017-08-17 21:11 UTC by p0m1d0rka

2017-08-18 11:16 UTC, vkurennov requested changes

2017-08-18 11:16 UTC, vkurennov commented on app/assets/javascripts/answers.coffee
> +$(document).on('turbolinks:update', answer_ready) # "вешаем" функцию ready на событие page:update
Это лишнее, достаточно только turbolinks:load.

2017-08-18 11:16 UTC, vkurennov commented on app/assets/javascripts/application.js
>  //= require rails-ujs
Нужно оставить либо jquery_ujs, либо rails-ujs, оба не нужны, будут потом проблемы.

2017-08-18 11:16 UTC, vkurennov commented on app/assets/javascripts/application.js
> +//= require_tree .
Эта строка должна быть последней в файле, сначала грузятся все файлы библиотек, потом уже пользовательские.

2017-08-18 11:16 UTC, vkurennov commented on app/assets/javascripts/questions.coffee
> +$(document).on('turbolinks:update', question_ready) # "вешаем" функцию ready на событие page:update
Это лишнее

2017-08-18 11:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      question.set_best_answer(answer)
Не совсем логично, это же действие над **ответом**, поэтому,  т.з. ООП, правильнее метод расположить в классе Answer

2017-08-18 11:16 UTC, vkurennov commented on app/models/answer.rb
> +  def self.bests
Это делается через скоупы

2017-08-18 11:16 UTC, vkurennov commented on app/models/answer.rb
> +  def self.best
Опять же это скоуп должен быть. И скорее всего, нужен только один скоуп, а не два. Еще можно сделать метод best_answer в модели вопроса, чтобы он возвращал лучший ответ

2017-08-18 11:16 UTC, vkurennov commented on app/models/answer.rb
> +  def best_answer?
Не нужно делать предикаты для флагов, рельсы их делают автоматом. Т.е. у тебя уже есть метод `is_best_flag?` Другое дело, что имя атрибута не очень красивое и поэтому и имя метода тоже не очень. Если бы было просто is_best, было бы лучше

2017-08-18 11:16 UTC, vkurennov commented on app/models/question.rb
> +  def set_best_answer(answer)
Действия полностью над ответами, методу не место в модели вопроса

2017-08-18 11:16 UTC, vkurennov commented on app/models/question.rb
> +      answer.update(is_best_flag: true)
Тут несколько апдейтов, поэтому нужно применить [транзакцию](api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2017-08-18 11:16 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +  $(".answer[data-answer-id=<%= @answer.id %>]").hide();
Лучше `remove()`

2017-08-18 11:16 UTC, vkurennov commented on config/routes.rb
> +      get 'set_as_best', on: :member
get-запросы никогда ничего не должны менять, это грубейшее нарушение REST-архитектуры и HTTP-протокола, используй post/patch для изменения данных на сервере. get-запросы только для получения данных

2017-08-18 11:16 UTC, vkurennov commented on spec/acceptance/answer/edit_answer_spec.rb
> +      sleep(3)
Думаю, 1 хватит

2017-08-18 11:16 UTC, vkurennov commented on spec/acceptance/answer/edit_answer_spec.rb
> +    scenario 'edit barely created answer', js: true do
Вообще, это частный случай редактирования обычного ответа, его не нужно отдельно тестировать.

2017-08-18 12:38 UTC, p0m1d0rka commented on app/assets/javascripts/application.js
>  //= require rails-ujs
оно и так отключено. С включенным двоятся xhr запросы. Удалю что б не смущало.

2017-08-18 12:40 UTC, p0m1d0rka commented on app/assets/javascripts/application.js
> +//= require_tree .
настроил в соответствии с гемом https://github.com/kossnocorp/jquery.turbolinks, который ты рекомендовал. 
там последним должны идти 
//= require turbolinks

2017-08-18 13:23 UTC, p0m1d0rka commented on spec/acceptance/answer/edit_answer_spec.rb
> +    scenario 'edit barely created answer', js: true do
тут попробовал по учебнику: воспроизводить баг в тесте, и потом его фиксить.

2017-08-19 09:42 UTC, vkurennov commented on app/assets/javascripts/application.js
> +//= require_tree .
Нет, там не совсем удачно описано. Имеется в виду, что нужно добавить эту строку после всех подключаемых скриптов, но пользовательские скрипты должны всегда идти в конце, уже после всех библиотек и гемов.

2017-08-19 09:45 UTC, vkurennov approved these changes

2017-08-19 09:45 UTC, vkurennov commented on app/assets/javascripts/application.js
> +//= require_tree .
В общем, я коммент оставил к твоему предыдущему, эта строка должна быть последней в файле.

2017-08-19 09:45 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(question) and question.answers.include?(answer)
Не используй and, or, not и т.п. Используй вместо них &&, ||, ! и т.п. У первых самый низкий приоритет, что может вести к сложноуловимым багам в условиях. Поэтому просто возьми за правило использовать операторы && и т.д.

2017-08-19 09:45 UTC, vkurennov commented on app/models/answer.rb
> +      self.update(is_best: true)
Транзакция откатится только в случае исключения, поэтому здесь должен быть `update!`

2017-08-19 09:45 UTC, vkurennov commented on app/models/question.rb
> +    self.answers.find_by(is_best: true)
Используй здесь скоуп bests из Answer

2017-08-19 09:45 UTC, vkurennov commented on spec/acceptance/answer/edit_answer_spec.rb
> +    scenario 'edit barely created answer', js: true do
ок

2017-08-19 16:39 UTC, merged