Lesson 9
p0m1d0rka/thinknetika17 pull request #8
Opened 2017-08-28 12:30 UTC by p0m1d0rka

Получилось не очень dry...
+ подскажи как тестировать модели, сейчас у меня получается дублирование с тестами контроллеров

2017-08-28 13:02 UTC, vkurennov requested changes

2017-08-28 13:02 UTC, vkurennov commented on .idea/.generators
> +<?xml version="1.0" encoding="UTF-8"?>
Нужно добавить папку .idea в .gitignore, т.к. разные разработчики могут использовать разные редакторы с разными настройками и им не нужны твои настройки, как и тебе настройки их редакторов.

2017-08-28 13:02 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    if @obj.vote?(current_user, 'up') || current_user.author_of?(@obj)
Для строк-идентификаторов лучше использовать символы, они для этого и нужны

2017-08-28 13:02 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      return true
1.  return не нужен, это же и так будет последнее выражение в методе.
2. Более того, if не нужен, как и явное возвращение true/false. Если прсото написать условное выражение, то оно и так вернет true/false, а раз это выражение последнее (и единственное в методе), то метод вернет то же значение.

2017-08-28 13:02 UTC, vkurennov commented on app/models/vote.rb
> +    self.ups.count - self.downs.count
Решение "в лоб" и поэтому очень неоптимальное. Чтобы подсчитать сумму тебе здесь приходтся сделать 2 запроса к базе и затем делать вычитание. А если в качестве значения голоса хранить +/- 1, то можно одной агрегатной функцией sum сразу получить общий рейтинг.

2017-08-28 13:02 UTC, vkurennov commented on spec/models/vote_spec.rb
> +  context '.vote?' do
Это методы в консерне моделей, и тесты должны быть в моделях Question и Answer

2017-08-28 13:02 UTC, vkurennov commented on spec/models/vote_spec.rb
> +    it 'destroy all votes on this obj on this user' do
Тут просто тестируешь, что делает метод. Даже если есть некоторое дублирование с тестами контроолеров не страшно, в контроллерах надо еще тестить ответы, а здесь только поведение самих методов. Далее мы изучим, как можно избавитсья от такого дублирования - будем проверять, что просто был вызыван нужный метод у модели в тестах контроллера, а сами тесты этих методов останутся в тестах контроллеров. Можешь и сейчас чуток вперед забежать и сделать это, поищи тему rspec message expectations

2017-08-28 14:58 UTC, vkurennov requested changes

2017-08-28 14:58 UTC, vkurennov commented on app/models/vote.rb
> +  scope :ups, -> { where(status: 'up') }
Скоупы поправь или убери вообще, они же не используются

2017-08-28 14:58 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        p.total_votes data-id=@question.id
Много дублирования с ответом, можно вынести в паршл. а для путей использовать [polymorphic_path](http://api.rubyonrails.org/v5.1/classes/ActionDispatch/Routing/PolymorphicRoutes.html)

2017-08-28 14:58 UTC, vkurennov commented on spec/acceptance/answer/vote_spec.rb
> +      expect(find('.total_votes').text.to_i).to eq old_votes-1
Можно без вычислений обойтись, просто проверить, что сначала, скажем, рейтинг 0, а потом -1 (или 1)

2017-08-28 14:58 UTC, vkurennov commented on spec/acceptance/answer/vote_spec.rb
> +    before do
Если в блоке одна строка, используй формат записи с фигруными скобками и в однострочиник

2017-08-28 14:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      it 'do nothing' do
Ну и зачем тогда такой тест? По идее, тут надо проверить, что кол-во голосов не меняется, чтобы быть уверемнным, что случайно их не удаляем

2017-08-28 14:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      it 'do nothing' do
Проверь, что кол-во голосов не меняется

2017-08-28 14:58 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.votes).to match_array(new_vote)
Не очевидная првоерка, лучше проверить, что кол-во голосов не изменилось. Кроме того, нужне еще и тесты на основное назначение метода - на создание голоса с нужным значением.

2017-08-28 14:58 UTC, vkurennov commented on spec/models/question_spec.rb
> +  context '.vote' do
Те же замечания, что и к тестам для модели Answer

2017-08-28 20:32 UTC, p0m1d0rka commented on spec/acceptance/answer/vote_spec.rb
> +      expect(find('.total_votes').text.to_i).to eq old_votes-1
да так по-моему честнее, + если добавим голоса в дальнейшем ничего не поедет.

2017-08-29 08:13 UTC, vkurennov approved these changes

2017-08-29 08:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before do
Используй однострочники

2017-08-29 08:13 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(new_vote.voteable_id).to eq answer2.id
Зачем по отдельным поля проверять? сравни votable с объектом и все. В тестах это допустимо, т.к. на производительность самого приложения не влияет.

2017-08-29 09:58 UTC, merged